build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production


#stages:
#  - build-mvn
#  - build-docker
#  - restart-compose
#
#build-mvn-microservices-stage:
#  stage: build-mvn
#  tags:
#    - microservices
#  only:
#    - master
#  script:
#    - mvn clean package -U -P prod -s settings.xml
#  artifacts:
#    paths:
#      - target/*.jar
#
#build-docker-microservices-stage:
#  stage: build-docker
#  needs:
#    - build-mvn-microservices-stage
#  tags:
#    - microservices
#  only:
#    - master
#  script:
#    - docker build -t order-service:latest --pull -f Dockerfile .
#  artifacts:
#    paths:
#      - target/*.jar
#
#restart-docker-microservices-compose:
#  stage: restart-compose
#  needs:
#    - build-docker-microservices-stage
#  tags:
#    - microservices
#  only:
#    - master
#  script:
#    - docker-compose -f /mcclinics/docker-compose.yml up -d
