spring:
  profiles:
    active: '@activatedProperties@'
  application:
    name: order-service
  freemarker:
    expose-request-attributes: true
#    template-loader-path: classpath:/resources/templates
#    suffix: .ftlh
  mustache:
    servlet:
      expose-request-attributes: true

springdoc:
    show-actuator: false
    swagger-ui:
        doc-expansion: none
        operations-sorter: method
        showCommonExtensions: true

management:
    endpoints:
        web:
            exposure:
                include: "*"

server:
  port: 8081
  servlet:
    encoding:
      force: true
      charset: UTF-8
