spring:
  profiles:
    active: '@activatedProperties@'
  application:
    name: order-service
  freemarker:
    expose-request-attributes: true
  mvc:
    dispatch-options-request: true
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
    show-actuator: false
    swagger-ui:
        doc-expansion: none
        operations-sorter: method
        showCommonExtensions: true

management:
    endpoints:
        web:
          exposure:
                include: "*"

server:
  port: 8081
  servlet:
    encoding:
      force: true
      charset: UTF-8
#keycloak:
#  auth-server-url: "https://sso.samsmu.ru/auth
#  realm: SAMGMU
#  resource: course

