spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/develop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
